### ISSUE TITLE
Broken java code

### ISSUE THREAD

**Issue by Philipp97714** [nadeldrucker/TrafficSwipe#11]
dev.nadeldrucker.trafficswipe.dao.transport.TransportApiFactory doesn't compile due to a missing library com.android.volley.RequestQueue

By the way, what's this class for?

**Comment by Philipp97714** [comment]
Same for dev.nadeldrucker.jvvo.*
What happend to that package? Please check if you added all required files to git.

**Comment by orlopau** [comment]
Compiles fine, https://github.com/nadeldrucker/TrafficSwipe/actions
