### ISSUE TITLE
Add animation

### ISSUE THREAD

**Issue by Philipp97714** [nadeldrucker/TrafficSwipe#3]
Find a way to implement a vector animation such as https://dribbble.com/shots/4787574-Organic-Artificial-Intelligence-design

- [x] turn on hardware acceleration

**Comment by Philipp97714** [comment]
@orlopau pls take a look to i003/animation branch

**Comment by orlopau** [comment]
Fixed problems in 554f219

**Comment by Philipp97714** [comment]
Required changes https://stackoverflow.com/questions/27626831/error-while-trying-to-test-animatedvectordrawable-cant-morph-from-x-to-z

Sources attached:

[svg.zip](https://github.com/nadeldrucker/TrafficSwipe/files/3785154/svg.zip)

**Comment by Philipp97714** [comment]
I temporarily turned off hardware acceleration for debugging purposes

**Comment by orlopau** [comment]
Fixed in 14c25f0

**Comment by Philipp97714** [comment]
@orlopau please check i003 branch
