### ISSUE TITLE
Make target TextView scrollable

### ISSUE THREAD

**Issue by Philipp97714** [nadeldrucker/TrafficSwipe#4]
In case of a name longer than the available space

**Comment by Philipp97714** [comment]
https://stackoverflow.com/questions/5472362/android-automatic-horizontally-scrolling-textview

**Comment by Philipp97714** [comment]
Waiting for @orlopau to fix #1 first

**Comment by orlopau** [comment]
I think that issue is not relevant atm, because the TextView was removed. :+1:

**Comment by orlopau** [comment]
My bad, the view still exists
